name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
    types: [synchronize, opened, reopened, edited]
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - example: default
            errors: 3
          - example: format-binary
            errors: 2
          - example: format-config
            errors: 1
          - example: format-ignore
            errors: 0
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          set -x

          cd example/${{ matrix.example }}

          if bazel build \
               --config=clang-format \
               --color=yes \
               //... 2>&1 | tee log; then
            [[ ${{ matrix.errors }} -eq 0 ]]
          else
            [[ ${{ matrix.errors }} -ne 0 ]]
          fi

          [[ ${{ matrix.errors }} -eq $(cat log | grep -c "Wclang-format-violations") ]]

  fix-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - example: default
          - example: format-binary
          - example: format-config
          - example: format-ignore
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          cd example/${{ matrix.example }}

          bazel build --config=clang-format-fix

          bazel build --config=clang-format

  all:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' }}
    needs:
      - check-format
      - fix-format
    steps:
    - run: true
