name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
    types: [synchronize, opened, reopened, edited]
  workflow_dispatch:

jobs:
  check-format:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - example: default
            errors: 3
          - example: format-binary
            errors: 2
          - example: format-config
            errors: 1
          - example: format-ignore
            errors: 0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          set -euxo pipefail

          cd example/${{ matrix.example }}

          if bazel build \
               --config=clang-format \
               --color=yes \
               //... 2>&1 | tee log; then
            [[ ${{ matrix.errors }} -eq 0 ]]
          else
            [[ ${{ matrix.errors }} -ne 0 ]]
          fi

          [[ ${{ matrix.errors }} -eq $(cat log | grep -c "Wclang-format-violations") ]]

  fix-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - default
          - format-binary
          - format-config
          - format-ignore
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          cd example/${{ matrix.example }}
          bazel build --config=clang-format-fix
          bazel build --config=clang-format

  bazel-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bazel_version:
          - latest
          - 7.x
          - 6.x
          - 5.x
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel_version }}
        run: |
          cd example/default

          version=${{ matrix.bazel_version }}

          if [[ "$version" == latest || "$version" < 7 ]]; then
            sed -i '/enable_bzlmod/d' .bazelrc
          fi

          bazel build --config=clang-format-fix

  # https://emmer.dev/blog/skippable-github-status-checks-aren-t-really-required/
  # https://github.com/marketplace/actions/alls-green
  all:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - check-format
      - fix-format
      - bazel-version
    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
